services:
  document_app:
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./documentapp:/app/documentapp
      - ./mysite:/app/mysite
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      document_app_db:
        condition: service_healthy
    networks:
      - document_app_shared_network

  document_app_db:
    image: postgres:17.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: document_app_user
      POSTGRES_PASSWORD: document_app_password
      POSTGRES_DB: document_app_db
    healthcheck:                                                                 
      test: ["CMD-SHELL", "pg_isready -d document_app_db -U document_app_user"]
      interval: 2s
      timeout: 30s
      retries: 15
    networks:
      - document_app_shared_network

volumes:
  postgres_data:

networks:
  document_app_shared_network:
    external: true
  document_app_private_network: