# Generated by Django 5.1.2 on 2024-10-29 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Item",
            new_name="Document",
        ),
    ]
