# Generated by Django 5.1.2 on 2024-11-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0002_rename_item_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.ImageField(default='images/name-of-image.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
