# Generated by Django 5.1.2 on 2024-11-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0005_boxcoordinate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxcoordinate',
            name='is_alphabetic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boxcoordinate',
            name='is_numeric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boxcoordinate',
            name='mean_lenght',
            field=models.IntegerField(default=0),
        ),
    ]
