# Generated by Django 5.1.2 on 2024-11-23 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentapp", "0008_rename_x1_box_end_x_rename_x2_box_end_y_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="box",
            old_name="mean_lenght",
            new_name="mean_length",
        ),
        migrations.AlterField(
            model_name="box",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="box",
                to="documentapp.document",
            ),
        ),
    ]
