# Generated by Django 5.1.2 on 2024-12-16 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0010_remove_box_end_x_remove_box_end_y_remove_box_start_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='document_samples/')),
                ('template_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_document', to='documentapp.document')),
            ],
        ),
        migrations.CreateModel(
            name='SampleBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('start_x_norm', models.FloatField()),
                ('start_y_norm', models.FloatField()),
                ('end_x_norm', models.FloatField()),
                ('end_y_norm', models.FloatField()),
                ('sample_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_box', to='documentapp.sampledocument')),
            ],
        ),
    ]
